package com.muhammdsamirkabirkhan.novaai.ui

import android.app.Application
import android.content.Context
import androidx.credentials.ClearCredentialStateRequest
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.NoCredentialException
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.auth.userProfileChangeRequest
import com.muhammdsamirkabirkhan.novaai.R
import com.muhammdsamirkabirkhan.novaai.ads.AdManager
import com.muhammdsamirkabirkhan.novaai.billing.BillingManager
import com.muhammdsamirkabirkhan.novaai.data.*
import com.muhammdsamirkabirkhan.novaai.friendly
import com.muhammdsamirkabirkhan.novaai.isQuota
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import kotlinx.coroutines.tasks.await

class MainViewModel(app: Application) : AndroidViewModel(app) {
    private val auth = FirebaseAuth.getInstance()
    private val _user = MutableStateFlow(auth.currentUser)
    val user: StateFlow<FirebaseUser?> = _user

    val busy = MutableStateFlow(false)
    val error = MutableStateFlow<String?>(null)
    val info = MutableStateFlow<String?>(null)

    @OptIn(ExperimentalCoroutinesApi::class)
    val profile: StateFlow<UserProfile?> = user
        .flatMapLatest { u -> if (u == null) flowOf(null) else Repo.profile(u.uid) }
        .stateIn(viewModelScope, SharingStarted.Eagerly, null)

    @OptIn(ExperimentalCoroutinesApi::class)
    val chats: StateFlow<List<ChatSummary>> = user
        .flatMapLatest { u -> if (u == null) flowOf(emptyList()) else Repo.chats() }
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5_000), emptyList())

    val billing = BillingManager(app, viewModelScope) { token, pid -> Repo.verifyPurchase(token, pid) }

    init {
        auth.addAuthStateListener { a ->
            _user.value = a.currentUser
            if (a.currentUser != null) viewModelScope.launch {
                Repo.bootstrap()          // creates users/{uid} on first login (server side)
                Repo.syncSubscription()   // refreshes Premium status from Google Play
                billing.connect()         // loads prices + silently re-verifies owned purchases
            }
        }
    }

    private fun authOp(block: suspend () -> Unit) {
        viewModelScope.launch {
            busy.value = true; error.value = null
            try { block() }
            catch (_: GetCredentialCancellationException) { }
            catch (_: NoCredentialException) { error.value = "No Google account found on this device." }
            catch (e: Exception) { error.value = e.friendly() }
            busy.value = false
        }
    }

    fun signIn(email: String, pw: String) = authOp { auth.signInWithEmailAndPassword(email.trim(), pw).await() }

    fun signUp(name: String, email: String, pw: String) = authOp {
        val r = auth.createUserWithEmailAndPassword(email.trim(), pw).await()
        r.user?.updateProfile(userProfileChangeRequest { displayName = name.trim() })?.await()
        r.user?.sendEmailVerification()
        Repo.bootstrap(name.trim())
    }

    fun google(activityCtx: Context) = authOp {
        val option = GetGoogleIdOption.Builder()
            .setFilterByAuthorizedAccounts(false)
            .setServerClientId(activityCtx.getString(R.string.default_web_client_id)) // generated by google-services
            .build()
        val res = CredentialManager.create(activityCtx)
            .getCredential(activityCtx, GetCredentialRequest.Builder().addCredentialOption(option).build())
        val cred = res.credential
        if (cred is CustomCredential && cred.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
            val token = GoogleIdTokenCredential.createFrom(cred.data).idToken
            auth.signInWithCredential(GoogleAuthProvider.getCredential(token, null)).await()
        } else error("Unsupported sign-in method.")
    }

    fun resetPassword(email: String) = authOp {
        auth.sendPasswordResetEmail(email.trim()).await()
        info.value = "If an account exists for that email, a reset link is on its way."
    }

    fun signOut(ctx: Context) {
        viewModelScope.launch {
            runCatching { CredentialManager.create(ctx).clearCredentialState(ClearCredentialStateRequest()) }
            auth.signOut()
        }
    }

    fun deleteAccount(ctx: Context) {
        viewModelScope.launch {
            busy.value = true
            Repo.deleteAccount()
                .onSuccess { signOut(ctx); info.value = "Your account and data were deleted." }
                .onFailure { error.value = it.friendly() }
            busy.value = false
        }
    }

    fun rename(name: String) {
        viewModelScope.launch { Repo.rename(name.trim().take(60)).onFailure { error.value = it.friendly() } }
    }

    fun deleteChat(id: String) {
        viewModelScope.launch { Repo.deleteChat(id).onFailure { error.value = it.friendly() } }
    }

    fun restorePurchases() { viewModelScope.launch { billing.restore(silent = false) } }
}

class ChatViewModel : ViewModel() {
    val chatId = MutableStateFlow<String?>(null)
    /** (text, message count when sent) - shown optimistically until the server copy arrives. */
    val pending = MutableStateFlow<Pair<String, Int>?>(null)
    val sending = MutableStateFlow(false)
    val error = MutableStateFlow<String?>(null)
    val quotaHit = MutableStateFlow(false)
    val notice = MutableStateFlow<String?>(null)
    private var lastText: String? = null

    @OptIn(ExperimentalCoroutinesApi::class)
    val messages: StateFlow<List<Message>> = chatId
        .flatMapLatest { id -> if (id == null) flowOf(emptyList()) else Repo.messages(id) }
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5_000), emptyList())

    fun newChat() { chatId.value = null; pending.value = null; error.value = null; lastText = null }
    fun open(id: String) { chatId.value = id; pending.value = null; error.value = null }
    fun clearError() { error.value = null; quotaHit.value = false }

    fun send(text: String, currentCount: Int) {
        val t = text.trim()
        if (t.isEmpty() || sending.value) return
        lastText = t
        pending.value = t to currentCount
        sending.value = true; error.value = null; quotaHit.value = false
        viewModelScope.launch {
            Repo.chat(chatId.value, t)
                .onSuccess { chatId.value = it.chatId; AdManager.onAction(); lastText = null }
                .onFailure { error.value = it.friendly(); quotaHit.value = it.isQuota }
            pending.value = null
            sending.value = false
        }
    }

    fun retry(currentCount: Int) { lastText?.let { send(it, currentCount) } }

    fun report(m: Message) {
        val id = chatId.value ?: return
        viewModelScope.launch {
            Repo.report(id, m.id)
                .onSuccess { notice.value = "Thanks - we'll review this response." }
                .onFailure { error.value = it.friendly() }
        }
    }
}

class ToolsViewModel : ViewModel() {
    data class UiState(val loading: Boolean = false, val result: String? = null, val error: String? = null, val quota: Boolean = false)
    val state = MutableStateFlow(UiState())

    fun run(tool: String, text: String, option: String) {
        if (state.value.loading) return
        state.value = UiState(loading = true)
        viewModelScope.launch {
            Repo.runTool(tool, text.trim(), option)
                .onSuccess { state.value = UiState(result = it); AdManager.onAction() }
                .onFailure { state.value = UiState(error = it.friendly(), quota = it.isQuota) }
        }
    }

    fun reset() { state.value = UiState() }
}
